// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Supplier.Infrastructure.DbContext;

#nullable disable

namespace Supplier.Infrastructure.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20260930181106_AddSupplierErpIntegration")]
    partial class AddSupplierErpIntegration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("supplier")
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Supplier.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AssetName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("asset_name");

                    b.Property<Guid?>("AssetType")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("asset_type");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("entity_id");

                    b.Property<Guid?>("EntityType")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("entity_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_name");

                    b.Property<Guid>("FileType")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("file_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_assets");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_assets_is_active");

                    b.ToTable("assets", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.CatalogAssetMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("asset_id");

                    b.Property<Guid>("CatalogId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("catalog_id");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_catalog_asset_mapping");

                    b.HasIndex("CatalogId")
                        .HasDatabaseName("ix_catalog_asset_mapping_catalog_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_catalog_asset_mapping_is_active");

                    b.ToTable("catalog_asset_mapping", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.RFQAttachmentMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("asset_id");

                    b.Property<Guid>("BuyerRFQId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("buyer_rfqid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("SupplierRFQId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_rfqid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_rfqattachment_mapping");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_rfqattachment_mapping_is_active");

                    b.HasIndex("SupplierRFQId")
                        .HasDatabaseName("ix_rfqattachment_mapping_supplier_rfqid");

                    b.ToTable("rfqattachment_mapping", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.RFQOrganizationUserMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("buyer_id");

                    b.Property<Guid>("BuyerRFQId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("buyer_rfqid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("organization_id");

                    b.Property<string>("RFQNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rfqnumber");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("SupplierRFQId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_rfqid");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_rfqorganization_user_mapping");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_rfqorganization_user_mapping_is_active");

                    b.HasIndex("SupplierRFQId")
                        .HasDatabaseName("ix_rfqorganization_user_mapping_supplier_rfqid");

                    b.ToTable("rfqorganization_user_mapping", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.RFQSupplierMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("buyer_id");

                    b.Property<Guid>("BuyerRFQId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("buyer_rfqid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("RFQNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rfqnumber");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("SupplierRFQId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_rfqid");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_rfqsupplier_mapping");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_rfqsupplier_mapping_is_active");

                    b.HasIndex("SupplierRFQId")
                        .HasDatabaseName("ix_rfqsupplier_mapping_supplier_rfqid");

                    b.ToTable("rfqsupplier_mapping", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierBankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AccountHolderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("account_holder_name");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("account_number");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bank_name");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("branch_name");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("currency");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<string>("IBAN")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("iban");

                    b.Property<string>("IFSCCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ifsccode");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit")
                        .HasColumnName("is_primary");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit")
                        .HasColumnName("is_verified");

                    b.Property<string>("SWIFTCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("swiftcode");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_supplier_bank_account");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_supplier_bank_account_is_active");

                    b.ToTable("supplier_bank_account", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierBusinessProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address_line2");

                    b.Property<decimal?>("AnnualTurnover")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("annual_turnover");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("business_type");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("city");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("country");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("currency");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<int?>("EmployeeCount")
                        .HasColumnType("int")
                        .HasColumnName("employee_count");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("industry");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("organization_id");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("organization_name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pin_code");

                    b.Property<string>("SNID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("snid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("state");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("website");

                    b.Property<int?>("YearEstablished")
                        .HasColumnType("int")
                        .HasColumnName("year_established");

                    b.HasKey("Id")
                        .HasName("pk_supplier_business_profile");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_supplier_business_profile_is_active");

                    b.ToTable("supplier_business_profile", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CatalogName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("catalog_name");

                    b.Property<string>("CatalogType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("catalog_type");

                    b.Property<long?>("Class")
                        .HasColumnType("bigint")
                        .HasColumnName("class");

                    b.Property<string>("ClassTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("class_title");

                    b.Property<long?>("Commodity")
                        .HasColumnType("bigint")
                        .HasColumnName("commodity");

                    b.Property<string>("CommodityTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("commodity_title");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("currency");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<long?>("Family")
                        .HasColumnType("bigint")
                        .HasColumnName("family");

                    b.Property<string>("FamilyTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("family_title");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPunchOut")
                        .HasColumnType("bit")
                        .HasColumnName("is_punch_out");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("PunchOutUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("punch_out_url");

                    b.Property<long?>("Segment")
                        .HasColumnType("bigint")
                        .HasColumnName("segment");

                    b.Property<string>("SegmentTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("segment_title");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_id");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("unit_of_measure");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_supplier_catalog");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_supplier_catalog_is_active");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_supplier_catalog_supplier_id");

                    b.ToTable("supplier_catalog", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<long?>("Class")
                        .HasColumnType("bigint")
                        .HasColumnName("class");

                    b.Property<string>("ClassTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("class_title");

                    b.Property<long?>("Commodity")
                        .HasColumnType("bigint")
                        .HasColumnName("commodity");

                    b.Property<string>("CommodityTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("commodity_title");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<long?>("Family")
                        .HasColumnType("bigint")
                        .HasColumnName("family");

                    b.Property<string>("FamilyTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("family_title");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<long>("Segment")
                        .HasColumnType("bigint")
                        .HasColumnName("segment");

                    b.Property<string>("SegmentTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("segment_title");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_supplier_category");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_supplier_category_is_active");

                    b.ToTable("supplier_category", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierDispatchLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address_line2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("city");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contact_person");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contact_phone");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("country");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit")
                        .HasColumnName("is_default");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("location_name");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pin_code");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("state");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_supplier_dispatch_location");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_supplier_dispatch_location_is_active");

                    b.ToTable("supplier_dispatch_location", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierEmailVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int")
                        .HasColumnName("attempt_count");

                    b.Property<Guid?>("BuyerRFQId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("buyer_rfqid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_on");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit")
                        .HasColumnName("is_verified");

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("otp_hash");

                    b.Property<string>("TemporaryVerificationToken")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("temporary_verification_token");

                    b.Property<DateTime?>("TemporaryVerificationTokenExpiresOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("temporary_verification_token_expires_on");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_supplier_email_verification");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_supplier_email_verification_is_active");

                    b.ToTable("supplier_email_verification", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierErpIntegrationConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AccessToken")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("access_token");

                    b.Property<string>("ApiKey")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("api_key");

                    b.Property<string>("ApiKeyHeader")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("api_key_header");

                    b.Property<string>("AuthPath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("auth_path");

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("auth_type");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("base_url");

                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("client_secret");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<string>("DefaultShipTo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("default_ship_to");

                    b.Property<string>("ErpType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("erp_type");

                    b.Property<string>("HeadersJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("headers_json");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("http_method");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("MaxRetryCount")
                        .HasColumnType("int")
                        .HasColumnName("max_retry_count");

                    b.Property<string>("OrderDateFormat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("order_date_format");

                    b.Property<string>("OrderPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("order_path");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("Scope")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("scope");

                    b.Property<Guid>("SupplierOrganizationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_organization_id");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("int")
                        .HasColumnName("timeout_seconds");

                    b.Property<string>("TokenUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("token_url");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("username");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_supplier_erp_integration_configuration");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_supplier_erp_integration_configuration_is_active");

                    b.ToTable("supplier_erp_integration_configuration", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierPurchaseDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("BuyerDocumentNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("buyer_document_number");

                    b.Property<string>("BuyerDocumentType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("buyer_document_type");

                    b.Property<Guid>("BuyerOrganizationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("buyer_organization_id");

                    b.Property<Guid?>("ConfigurationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("configuration_id");

                    b.Property<int>("ConfigurationVersion")
                        .HasColumnType("int")
                        .HasColumnName("configuration_version");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("correlation_id");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error_message");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("idempotency_key");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastAttemptOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_attempt_on");

                    b.Property<bool>("OutcomeUnknown")
                        .HasColumnType("bit")
                        .HasColumnName("outcome_unknown");

                    b.Property<string>("ResolvedBaseUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("resolved_base_url");

                    b.Property<string>("ResolvedOrderPath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("resolved_order_path");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_body");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int")
                        .HasColumnName("retry_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("SupplierDocumentNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("supplier_document_number");

                    b.Property<string>("SupplierDocumentType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("supplier_document_type");

                    b.Property<Guid>("SupplierOrganizationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_organization_id");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("WishlistId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("wishlist_id");

                    b.HasKey("Id")
                        .HasName("pk_supplier_purchase_document");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_supplier_purchase_document_idempotency_key");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_supplier_purchase_document_is_active");

                    b.ToTable("supplier_purchase_document", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierQuotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("buyer_id");

                    b.Property<Guid>("BuyerRFQId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("buyer_rfqid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<decimal?>("DeliveryCharge")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("delivery_charge");

                    b.Property<string>("DeliveryType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("delivery_type");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount");

                    b.Property<string>("DiscountType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("discount_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("RFQNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rfqnumber");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("SupplierRFQId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_rfqid");

                    b.Property<decimal?>("Tax")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax");

                    b.Property<string>("TaxType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tax_type");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_price");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_supplier_quotation");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_supplier_quotation_is_active");

                    b.HasIndex("SupplierRFQId")
                        .HasDatabaseName("ix_supplier_quotation_supplier_rfqid");

                    b.ToTable("supplier_quotation", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierQuotationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("buyer_id");

                    b.Property<Guid>("BuyerRFQId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("buyer_rfqid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<decimal?>("DeliveryCharge")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("delivery_charge");

                    b.Property<string>("DeliveryType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("delivery_type");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount");

                    b.Property<string>("DiscountType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("discount_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("RFQNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rfqnumber");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("SupplierQuotationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_quotation_id");

                    b.Property<Guid>("SupplierRFQId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_rfqid");

                    b.Property<decimal?>("Tax")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax");

                    b.Property<string>("TaxType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tax_type");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_price");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_supplier_quotation_history");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_supplier_quotation_history_is_active");

                    b.HasIndex("SupplierQuotationId")
                        .HasDatabaseName("ix_supplier_quotation_history_supplier_quotation_id");

                    b.ToTable("supplier_quotation_history", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierQuotationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("buyer_id");

                    b.Property<Guid>("BuyerRFQId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("buyer_rfqid");

                    b.Property<Guid>("BuyerRFQItemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("buyer_rfqitem_id");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<decimal?>("DeliveryCharge")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("delivery_charge");

                    b.Property<string>("DeliveryType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("delivery_type");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount");

                    b.Property<string>("DiscountType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("discount_type");

                    b.Property<bool>("ISLineitemAvailable")
                        .HasColumnType("bit")
                        .HasColumnName("islineitem_available");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<decimal>("QuotedAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("quoted_amount");

                    b.Property<decimal>("QuotedPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("quoted_price");

                    b.Property<string>("RFQNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rfqnumber");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("sub_total");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("SupplierQuotationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_quotation_id");

                    b.Property<Guid>("SupplierRFQItemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_rfqitem_id");

                    b.Property<decimal?>("Tax")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax");

                    b.Property<string>("TaxType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tax_type");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_supplier_quotation_item");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_supplier_quotation_item_is_active");

                    b.HasIndex("SupplierQuotationId")
                        .HasDatabaseName("ix_supplier_quotation_item_supplier_quotation_id");

                    b.HasIndex("SupplierRFQItemId")
                        .HasDatabaseName("ix_supplier_quotation_item_supplier_rfqitem_id");

                    b.ToTable("supplier_quotation_item", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierQuotationItemHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("buyer_id");

                    b.Property<Guid>("BuyerRFQId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("buyer_rfqid");

                    b.Property<Guid>("BuyerRFQItemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("buyer_rfqitem_id");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<decimal?>("DeliveryCharge")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("delivery_charge");

                    b.Property<string>("DeliveryType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("delivery_type");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount");

                    b.Property<string>("DiscountType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("discount_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<decimal>("QuotedAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("quoted_amount");

                    b.Property<decimal>("QuotedPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("quoted_price");

                    b.Property<string>("RFQNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rfqnumber");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("sub_total");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("SupplierQuotationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_quotation_id");

                    b.Property<Guid>("SupplierQuotationItemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_quotation_item_id");

                    b.Property<Guid>("SupplierRFQItemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_rfqitem_id");

                    b.Property<decimal?>("Tax")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax");

                    b.Property<string>("TaxType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tax_type");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_supplier_quotation_item_history");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_supplier_quotation_item_history_is_active");

                    b.HasIndex("SupplierQuotationId")
                        .HasDatabaseName("ix_supplier_quotation_item_history_supplier_quotation_id");

                    b.ToTable("supplier_quotation_item_history", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierRFQ", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("AddLotOption")
                        .HasColumnType("bit")
                        .HasColumnName("add_lot_option");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("buyer_id");

                    b.Property<string>("BuyerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("buyer_name");

                    b.Property<Guid>("BuyerRFQId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("buyer_rfqid");

                    b.Property<string>("BuyerTermsAndConditionAccepted")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("buyer_terms_and_condition_accepted");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("currency");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<string>("DeliveryLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("delivery_location");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSupplierInvitedForContract")
                        .HasColumnType("bit")
                        .HasColumnName("is_supplier_invited_for_contract");

                    b.Property<string>("RFQNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rfqnumber");

                    b.Property<string>("SessionToken")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("session_token");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_id");

                    b.Property<bool>("TermsAndCondition")
                        .HasColumnType("bit")
                        .HasColumnName("terms_and_condition");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_supplier_rfq");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_supplier_rfq_is_active");

                    b.ToTable("supplier_rfq", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierRFQAnswerOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<Guid>("RFQQuestionOptionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("rfqquestion_option_id");

                    b.Property<Guid>("SupplierRFQQuestionAnswerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_rfqquestion_answer_id");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_supplier_rfqanswer_option");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_supplier_rfqanswer_option_is_active");

                    b.ToTable("supplier_rfqanswer_option", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierRFQItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("AwardedSupplierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("awarded_supplier_id");

                    b.Property<Guid>("BuyerRFQItemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("buyer_rfqitem_id");

                    b.Property<string>("CostCenter")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cost_center");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAwarded")
                        .HasColumnType("bit")
                        .HasColumnName("is_awarded");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int")
                        .HasColumnName("line_number");

                    b.Property<string>("MaterialCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("material_code");

                    b.Property<string>("MaterialGroup")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("material_group");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SupplierRFQId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_rfqid");

                    b.Property<string>("UOM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("uom");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_supplier_rfqitem");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_supplier_rfqitem_is_active");

                    b.HasIndex("SupplierRFQId")
                        .HasDatabaseName("ix_supplier_rfqitem_supplier_rfqid");

                    b.ToTable("supplier_rfqitem", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierRFQQuestionAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("answer");

                    b.Property<DateTime?>("AnsweredOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("answered_on");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("asset_id");

                    b.Property<Guid>("BuyerRFQId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("buyer_rfqid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<Guid?>("QuestionOptionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("question_option_id");

                    b.Property<string>("RFQNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rfqnumber");

                    b.Property<Guid>("RFQQuestionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("rfqquestion_id");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("SupplierRFQId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_rfqid");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_supplier_rfqquestion_answer");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_supplier_rfqquestion_answer_is_active");

                    b.ToTable("supplier_rfqquestion_answer", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("asset_id");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("expiry_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit")
                        .HasColumnName("is_verified");

                    b.Property<string>("RegistrationName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("registration_name");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("registration_number");

                    b.Property<string>("RegistrationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("registration_type");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("VerifiedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("verified_on");

                    b.HasKey("Id")
                        .HasName("pk_supplier_registration");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_supplier_registration_is_active");

                    b.ToTable("supplier_registration", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierVerificationAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("answer");

                    b.Property<DateTime?>("AnsweredOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("answered_on");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("asset_id");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("SupplierVerificationRequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_verification_request_id");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("template_id");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("VerificationTemplateQuestionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("verification_template_question_id");

                    b.Property<Guid?>("VerificationTemplateQuestionOptionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("verification_template_question_option_id");

                    b.HasKey("Id")
                        .HasName("pk_supplier_verification_answer");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_supplier_verification_answer_is_active");

                    b.ToTable("supplier_verification_answer", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierVerificationAnswerOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<Guid>("SupplierVerificationAnswerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_verification_answer_id");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("VerificationTemplateQuestionOptionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("verification_template_question_option_id");

                    b.HasKey("Id")
                        .HasName("pk_supplier_verification_answer_option");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_supplier_verification_answer_option_is_active");

                    b.ToTable("supplier_verification_answer_option", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.CatalogAssetMapping", b =>
                {
                    b.HasOne("Supplier.Domain.Entities.SupplierCatalog", "SupplierCatalog")
                        .WithMany()
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_catalog_asset_mapping_supplier_catalog_catalog_id");

                    b.Navigation("SupplierCatalog");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.RFQAttachmentMapping", b =>
                {
                    b.HasOne("Supplier.Domain.Entities.SupplierRFQ", "SupplierRFQ")
                        .WithMany()
                        .HasForeignKey("SupplierRFQId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rfqattachment_mapping_supplier_rfq_supplier_rfqid");

                    b.Navigation("SupplierRFQ");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.RFQOrganizationUserMapping", b =>
                {
                    b.HasOne("Supplier.Domain.Entities.SupplierRFQ", "SupplierRFQ")
                        .WithMany()
                        .HasForeignKey("SupplierRFQId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rfqorganization_user_mapping_supplier_rfq_supplier_rfqid");

                    b.Navigation("SupplierRFQ");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.RFQSupplierMapping", b =>
                {
                    b.HasOne("Supplier.Domain.Entities.SupplierRFQ", "SupplierRFQ")
                        .WithMany()
                        .HasForeignKey("SupplierRFQId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rfqsupplier_mapping_supplier_rfq_supplier_rfqid");

                    b.Navigation("SupplierRFQ");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierCatalog", b =>
                {
                    b.HasOne("Supplier.Domain.Entities.SupplierBusinessProfile", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_supplier_catalog_supplier_business_profile_supplier_id");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierQuotation", b =>
                {
                    b.HasOne("Supplier.Domain.Entities.SupplierRFQ", "SupplierRFQ")
                        .WithMany()
                        .HasForeignKey("SupplierRFQId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_supplier_quotation_supplier_rfq_supplier_rfqid");

                    b.Navigation("SupplierRFQ");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierQuotationHistory", b =>
                {
                    b.HasOne("Supplier.Domain.Entities.SupplierQuotation", "SupplierQuotation")
                        .WithMany()
                        .HasForeignKey("SupplierQuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_supplier_quotation_history_supplier_quotation_supplier_quotation_id");

                    b.Navigation("SupplierQuotation");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierQuotationItem", b =>
                {
                    b.HasOne("Supplier.Domain.Entities.SupplierQuotation", "SupplierQuotation")
                        .WithMany()
                        .HasForeignKey("SupplierQuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_supplier_quotation_item_supplier_quotation_supplier_quotation_id");

                    b.HasOne("Supplier.Domain.Entities.SupplierRFQItem", "SupplierRFQItem")
                        .WithMany()
                        .HasForeignKey("SupplierRFQItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_supplier_quotation_item_supplier_rfqitem_supplier_rfqitem_id");

                    b.Navigation("SupplierQuotation");

                    b.Navigation("SupplierRFQItem");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierQuotationItemHistory", b =>
                {
                    b.HasOne("Supplier.Domain.Entities.SupplierQuotation", "SupplierQuotation")
                        .WithMany()
                        .HasForeignKey("SupplierQuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_supplier_quotation_item_history_supplier_quotation_supplier_quotation_id");

                    b.Navigation("SupplierQuotation");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierRFQItem", b =>
                {
                    b.HasOne("Supplier.Domain.Entities.SupplierRFQ", "SupplierRFQ")
                        .WithMany()
                        .HasForeignKey("SupplierRFQId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_supplier_rfqitem_supplier_rfq_supplier_rfqid");

                    b.Navigation("SupplierRFQ");
                });
#pragma warning restore 612, 618
        }
    }
}
