// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Supplier.Infrastructure.DbContext;

#nullable disable

namespace Supplier.Infrastructure.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20260803095321_UpdateSupplierCatalogUnspscFields")]
    partial class UpdateSupplierCatalogUnspscFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("supplier")
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Supplier.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AssetName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("asset_name");

                    b.Property<Guid?>("AssetType")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("asset_type");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("entity_id");

                    b.Property<Guid?>("EntityType")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("entity_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_name");

                    b.Property<Guid>("FileType")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("file_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_assets");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_assets_is_active");

                    b.ToTable("assets", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.CatalogAssetMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("asset_id");

                    b.Property<Guid>("CatalogId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("catalog_id");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_catalog_asset_mapping");

                    b.HasIndex("CatalogId")
                        .HasDatabaseName("ix_catalog_asset_mapping_catalog_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_catalog_asset_mapping_is_active");

                    b.ToTable("catalog_asset_mapping", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.RFQSupplierMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("buyer_id");

                    b.Property<Guid>("BuyerRFQId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("buyer_rfqid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("RFQNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rfqnumber");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("SupplierRFQId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_rfqid");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_rfqsupplier_mapping");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_rfqsupplier_mapping_is_active");

                    b.HasIndex("SupplierRFQId")
                        .HasDatabaseName("ix_rfqsupplier_mapping_supplier_rfqid");

                    b.ToTable("rfqsupplier_mapping", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierBankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AccountHolderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("account_holder_name");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("account_number");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bank_name");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("branch_name");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("currency");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<string>("IBAN")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("iban");

                    b.Property<string>("IFSCCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ifsccode");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit")
                        .HasColumnName("is_primary");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit")
                        .HasColumnName("is_verified");

                    b.Property<string>("SWIFTCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("swiftcode");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_supplier_bank_account");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_supplier_bank_account_is_active");

                    b.ToTable("supplier_bank_account", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierBusinessProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address_line2");

                    b.Property<decimal?>("AnnualTurnover")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("annual_turnover");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("business_type");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("city");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("country");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("currency");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<int?>("EmployeeCount")
                        .HasColumnType("int")
                        .HasColumnName("employee_count");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("industry");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("organization_id");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("organization_name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pin_code");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("state");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("website");

                    b.Property<int?>("YearEstablished")
                        .HasColumnType("int")
                        .HasColumnName("year_established");

                    b.HasKey("Id")
                        .HasName("pk_supplier_business_profile");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_supplier_business_profile_is_active");

                    b.ToTable("supplier_business_profile", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CatalogName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("catalog_name");

                    b.Property<string>("CatalogType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("catalog_type");

                    b.Property<long?>("Class")
                        .HasColumnType("bigint")
                        .HasColumnName("class");

                    b.Property<string>("ClassTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("class_title");

                    b.Property<long?>("Commodity")
                        .HasColumnType("bigint")
                        .HasColumnName("commodity");

                    b.Property<string>("CommodityTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("commodity_title");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<long?>("Family")
                        .HasColumnType("bigint")
                        .HasColumnName("family");

                    b.Property<string>("FamilyTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("family_title");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPunchOut")
                        .HasColumnType("bit")
                        .HasColumnName("is_punch_out");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("PunchOutUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("punch_out_url");

                    b.Property<long?>("Segment")
                        .HasColumnType("bigint")
                        .HasColumnName("segment");

                    b.Property<string>("SegmentTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("segment_title");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_id");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("unit_of_measure");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_supplier_catalog");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_supplier_catalog_is_active");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_supplier_catalog_supplier_id");

                    b.ToTable("supplier_catalog", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<long?>("Class")
                        .HasColumnType("bigint")
                        .HasColumnName("class");

                    b.Property<string>("ClassTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("class_title");

                    b.Property<long?>("Commodity")
                        .HasColumnType("bigint")
                        .HasColumnName("commodity");

                    b.Property<string>("CommodityTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("commodity_title");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<long?>("Family")
                        .HasColumnType("bigint")
                        .HasColumnName("family");

                    b.Property<string>("FamilyTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("family_title");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<long>("Segment")
                        .HasColumnType("bigint")
                        .HasColumnName("segment");

                    b.Property<string>("SegmentTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("segment_title");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_supplier_category");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_supplier_category_is_active");

                    b.ToTable("supplier_category", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierDispatchLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address_line2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("city");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contact_person");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contact_phone");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("country");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit")
                        .HasColumnName("is_default");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("location_name");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pin_code");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("state");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_supplier_dispatch_location");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_supplier_dispatch_location_is_active");

                    b.ToTable("supplier_dispatch_location", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierQuotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("buyer_id");

                    b.Property<Guid>("BuyerRFQId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("buyer_rfqid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<decimal?>("DeliveryCharge")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("delivery_charge");

                    b.Property<string>("DeliveryType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("delivery_type");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount");

                    b.Property<string>("DiscountType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("discount_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("RFQNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rfqnumber");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("SupplierRFQId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_rfqid");

                    b.Property<decimal?>("Tax")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax");

                    b.Property<string>("TaxType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tax_type");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_price");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_supplier_quotation");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_supplier_quotation_is_active");

                    b.HasIndex("SupplierRFQId")
                        .HasDatabaseName("ix_supplier_quotation_supplier_rfqid");

                    b.ToTable("supplier_quotation", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierQuotationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("buyer_id");

                    b.Property<Guid>("BuyerRFQId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("buyer_rfqid");

                    b.Property<Guid>("BuyerRFQItemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("buyer_rfqitem_id");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<decimal>("QuotedPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("quoted_price");

                    b.Property<string>("RFQNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rfqnumber");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("SupplierQuotationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_quotation_id");

                    b.Property<Guid>("SupplierRFQItemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_rfqitem_id");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_supplier_quotation_item");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_supplier_quotation_item_is_active");

                    b.HasIndex("SupplierQuotationId")
                        .HasDatabaseName("ix_supplier_quotation_item_supplier_quotation_id");

                    b.HasIndex("SupplierRFQItemId")
                        .HasDatabaseName("ix_supplier_quotation_item_supplier_rfqitem_id");

                    b.ToTable("supplier_quotation_item", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierRFQ", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("AddLotOption")
                        .HasColumnType("bit")
                        .HasColumnName("add_lot_option");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("buyer_id");

                    b.Property<string>("BuyerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("buyer_name");

                    b.Property<Guid>("BuyerRFQId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("buyer_rfqid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<string>("DeliveryLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("delivery_location");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("RFQNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rfqnumber");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_supplier_rfq");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_supplier_rfq_is_active");

                    b.ToTable("supplier_rfq", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierRFQAnswerOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<Guid>("RFQQuestionOptionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("rfqquestion_option_id");

                    b.Property<Guid>("SupplierRFQQuestionAnswerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_rfqquestion_answer_id");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_supplier_rfqanswer_option");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_supplier_rfqanswer_option_is_active");

                    b.ToTable("supplier_rfqanswer_option", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierRFQItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("BuyerRFQItemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("buyer_rfqitem_id");

                    b.Property<string>("CostCenter")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cost_center");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("MaterialCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("material_code");

                    b.Property<string>("MaterialGroup")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("material_group");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SupplierRFQId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_rfqid");

                    b.Property<string>("UOM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("uom");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_supplier_rfqitem");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_supplier_rfqitem_is_active");

                    b.HasIndex("SupplierRFQId")
                        .HasDatabaseName("ix_supplier_rfqitem_supplier_rfqid");

                    b.ToTable("supplier_rfqitem", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierRFQQuestionAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("answer");

                    b.Property<DateTime?>("AnsweredOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("answered_on");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("asset_id");

                    b.Property<Guid>("BuyerRFQId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("buyer_rfqid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<Guid?>("QuestionOptionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("question_option_id");

                    b.Property<string>("RFQNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rfqnumber");

                    b.Property<Guid>("RFQQuestionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("rfqquestion_id");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("SupplierRFQId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_rfqid");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_supplier_rfqquestion_answer");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_supplier_rfqquestion_answer_is_active");

                    b.ToTable("supplier_rfqquestion_answer", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("asset_id");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("expiry_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit")
                        .HasColumnName("is_verified");

                    b.Property<string>("RegistrationName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("registration_name");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("registration_number");

                    b.Property<string>("RegistrationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("registration_type");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("VerifiedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("verified_on");

                    b.HasKey("Id")
                        .HasName("pk_supplier_registration");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_supplier_registration_is_active");

                    b.ToTable("supplier_registration", "supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.CatalogAssetMapping", b =>
                {
                    b.HasOne("Supplier.Domain.Entities.SupplierCatalog", "SupplierCatalog")
                        .WithMany()
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_catalog_asset_mapping_supplier_catalog_catalog_id");

                    b.Navigation("SupplierCatalog");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.RFQSupplierMapping", b =>
                {
                    b.HasOne("Supplier.Domain.Entities.SupplierRFQ", "SupplierRFQ")
                        .WithMany()
                        .HasForeignKey("SupplierRFQId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rfqsupplier_mapping_supplier_rfq_supplier_rfqid");

                    b.Navigation("SupplierRFQ");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierCatalog", b =>
                {
                    b.HasOne("Supplier.Domain.Entities.SupplierBusinessProfile", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_supplier_catalog_supplier_business_profile_supplier_id");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierQuotation", b =>
                {
                    b.HasOne("Supplier.Domain.Entities.SupplierRFQ", "SupplierRFQ")
                        .WithMany()
                        .HasForeignKey("SupplierRFQId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_supplier_quotation_supplier_rfq_supplier_rfqid");

                    b.Navigation("SupplierRFQ");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierQuotationItem", b =>
                {
                    b.HasOne("Supplier.Domain.Entities.SupplierQuotation", "SupplierQuotation")
                        .WithMany()
                        .HasForeignKey("SupplierQuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_supplier_quotation_item_supplier_quotation_supplier_quotation_id");

                    b.HasOne("Supplier.Domain.Entities.SupplierRFQItem", "SupplierRFQItem")
                        .WithMany()
                        .HasForeignKey("SupplierRFQItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_supplier_quotation_item_supplier_rfqitem_supplier_rfqitem_id");

                    b.Navigation("SupplierQuotation");

                    b.Navigation("SupplierRFQItem");
                });

            modelBuilder.Entity("Supplier.Domain.Entities.SupplierRFQItem", b =>
                {
                    b.HasOne("Supplier.Domain.Entities.SupplierRFQ", "SupplierRFQ")
                        .WithMany()
                        .HasForeignKey("SupplierRFQId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_supplier_rfqitem_supplier_rfq_supplier_rfqid");

                    b.Navigation("SupplierRFQ");
                });
#pragma warning restore 612, 618
        }
    }
}
